/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as ClientRouteImport } from './routes/_client'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ClientIndexRouteImport } from './routes/_client/index'
import { Route as RegisterProviderRouteImport } from './routes/register/provider'
import { Route as RegisterClientRouteImport } from './routes/register/client'
import { Route as Onboarding3RouteImport } from './routes/onboarding/3'
import { Route as Onboarding2RouteImport } from './routes/onboarding/2'
import { Route as Onboarding1RouteImport } from './routes/onboarding/1'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardScheduledEventsRouteImport } from './routes/_dashboard/scheduled-events'
import { Route as DashboardIntegrationsRouteImport } from './routes/_dashboard/integrations'
import { Route as DashboardEventTypesRouteImport } from './routes/_dashboard/event-types'
import { Route as DashboardAvailabilityRouteImport } from './routes/_dashboard/availability'
import { Route as ClientProviderSlugRouteImport } from './routes/_client/$providerSlug'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const RegisterProviderRoute = RegisterProviderRouteImport.update({
  id: '/register/provider',
  path: '/register/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterClientRoute = RegisterClientRouteImport.update({
  id: '/register/client',
  path: '/register/client',
  getParentRoute: () => rootRouteImport,
} as any)
const Onboarding3Route = Onboarding3RouteImport.update({
  id: '/onboarding/3',
  path: '/onboarding/3',
  getParentRoute: () => rootRouteImport,
} as any)
const Onboarding2Route = Onboarding2RouteImport.update({
  id: '/onboarding/2',
  path: '/onboarding/2',
  getParentRoute: () => rootRouteImport,
} as any)
const Onboarding1Route = Onboarding1RouteImport.update({
  id: '/onboarding/1',
  path: '/onboarding/1',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScheduledEventsRoute =
  DashboardScheduledEventsRouteImport.update({
    id: '/scheduled-events',
    path: '/scheduled-events',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventTypesRoute = DashboardEventTypesRouteImport.update({
  id: '/event-types',
  path: '/event-types',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAvailabilityRoute = DashboardAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => DashboardRoute,
} as any)
const ClientProviderSlugRoute = ClientProviderSlugRouteImport.update({
  id: '/$providerSlug',
  path: '/$providerSlug',
  getParentRoute: () => ClientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ClientIndexRoute
  '/$providerSlug': typeof ClientProviderSlugRoute
  '/availability': typeof DashboardAvailabilityRoute
  '/event-types': typeof DashboardEventTypesRoute
  '/integrations': typeof DashboardIntegrationsRoute
  '/scheduled-events': typeof DashboardScheduledEventsRoute
  '/settings': typeof DashboardSettingsRoute
  '/onboarding/1': typeof Onboarding1Route
  '/onboarding/2': typeof Onboarding2Route
  '/onboarding/3': typeof Onboarding3Route
  '/register/client': typeof RegisterClientRoute
  '/register/provider': typeof RegisterProviderRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ClientIndexRoute
  '/$providerSlug': typeof ClientProviderSlugRoute
  '/availability': typeof DashboardAvailabilityRoute
  '/event-types': typeof DashboardEventTypesRoute
  '/integrations': typeof DashboardIntegrationsRoute
  '/scheduled-events': typeof DashboardScheduledEventsRoute
  '/settings': typeof DashboardSettingsRoute
  '/onboarding/1': typeof Onboarding1Route
  '/onboarding/2': typeof Onboarding2Route
  '/onboarding/3': typeof Onboarding3Route
  '/register/client': typeof RegisterClientRoute
  '/register/provider': typeof RegisterProviderRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_client': typeof ClientRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_client/$providerSlug': typeof ClientProviderSlugRoute
  '/_dashboard/availability': typeof DashboardAvailabilityRoute
  '/_dashboard/event-types': typeof DashboardEventTypesRoute
  '/_dashboard/integrations': typeof DashboardIntegrationsRoute
  '/_dashboard/scheduled-events': typeof DashboardScheduledEventsRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/onboarding/1': typeof Onboarding1Route
  '/onboarding/2': typeof Onboarding2Route
  '/onboarding/3': typeof Onboarding3Route
  '/register/client': typeof RegisterClientRoute
  '/register/provider': typeof RegisterProviderRoute
  '/_client/': typeof ClientIndexRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$providerSlug'
    | '/availability'
    | '/event-types'
    | '/integrations'
    | '/scheduled-events'
    | '/settings'
    | '/onboarding/1'
    | '/onboarding/2'
    | '/onboarding/3'
    | '/register/client'
    | '/register/provider'
    | '/login/'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$providerSlug'
    | '/availability'
    | '/event-types'
    | '/integrations'
    | '/scheduled-events'
    | '/settings'
    | '/onboarding/1'
    | '/onboarding/2'
    | '/onboarding/3'
    | '/register/client'
    | '/register/provider'
    | '/login'
    | '/register'
  id:
    | '__root__'
    | '/_client'
    | '/_dashboard'
    | '/_client/$providerSlug'
    | '/_dashboard/availability'
    | '/_dashboard/event-types'
    | '/_dashboard/integrations'
    | '/_dashboard/scheduled-events'
    | '/_dashboard/settings'
    | '/onboarding/1'
    | '/onboarding/2'
    | '/onboarding/3'
    | '/register/client'
    | '/register/provider'
    | '/_client/'
    | '/login/'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ClientRoute: typeof ClientRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  Onboarding1Route: typeof Onboarding1Route
  Onboarding2Route: typeof Onboarding2Route
  Onboarding3Route: typeof Onboarding3Route
  RegisterClientRoute: typeof RegisterClientRoute
  RegisterProviderRoute: typeof RegisterProviderRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/': {
      id: '/_client/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/register/provider': {
      id: '/register/provider'
      path: '/register/provider'
      fullPath: '/register/provider'
      preLoaderRoute: typeof RegisterProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/client': {
      id: '/register/client'
      path: '/register/client'
      fullPath: '/register/client'
      preLoaderRoute: typeof RegisterClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/3': {
      id: '/onboarding/3'
      path: '/onboarding/3'
      fullPath: '/onboarding/3'
      preLoaderRoute: typeof Onboarding3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/2': {
      id: '/onboarding/2'
      path: '/onboarding/2'
      fullPath: '/onboarding/2'
      preLoaderRoute: typeof Onboarding2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/1': {
      id: '/onboarding/1'
      path: '/onboarding/1'
      fullPath: '/onboarding/1'
      preLoaderRoute: typeof Onboarding1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/scheduled-events': {
      id: '/_dashboard/scheduled-events'
      path: '/scheduled-events'
      fullPath: '/scheduled-events'
      preLoaderRoute: typeof DashboardScheduledEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/integrations': {
      id: '/_dashboard/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/event-types': {
      id: '/_dashboard/event-types'
      path: '/event-types'
      fullPath: '/event-types'
      preLoaderRoute: typeof DashboardEventTypesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/availability': {
      id: '/_dashboard/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof DashboardAvailabilityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_client/$providerSlug': {
      id: '/_client/$providerSlug'
      path: '/$providerSlug'
      fullPath: '/$providerSlug'
      preLoaderRoute: typeof ClientProviderSlugRouteImport
      parentRoute: typeof ClientRoute
    }
  }
}

interface ClientRouteChildren {
  ClientProviderSlugRoute: typeof ClientProviderSlugRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientProviderSlugRoute: ClientProviderSlugRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface DashboardRouteChildren {
  DashboardAvailabilityRoute: typeof DashboardAvailabilityRoute
  DashboardEventTypesRoute: typeof DashboardEventTypesRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardScheduledEventsRoute: typeof DashboardScheduledEventsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAvailabilityRoute: DashboardAvailabilityRoute,
  DashboardEventTypesRoute: DashboardEventTypesRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardScheduledEventsRoute: DashboardScheduledEventsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ClientRoute: ClientRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  Onboarding1Route: Onboarding1Route,
  Onboarding2Route: Onboarding2Route,
  Onboarding3Route: Onboarding3Route,
  RegisterClientRoute: RegisterClientRoute,
  RegisterProviderRoute: RegisterProviderRoute,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
